### ISSUE TITLE
Incomplete revert of saved state when buffer file goes missing

### ISSUE THREAD

**Issue by jdtsmith** [alphapapa/activities.el#17]
`activities-revert` from within a window in a modified activity frame (different buffers showing) reverts only _some_ of the windows. When called from a window containing a correct buffer from the activity, it works as expected to restore other windows. 

For example a given activity contains 3 window/buffer combos, A, B, and C. If A and B are altered to show other non-activity buffers (e.g. with winner), to say an A', B', C, calling activities-resume from A' might lead to a spurious C, B', C configuration. 

I think I have identified the reason for this.  If one of the files (say A's) has gone missing, due to changing git branches, for example, on revert its window will reappear, but the buffer contents of the window will be arbitrary, sometimes selecting a file from the activity, or another file altogether.  

Here perhaps a _warning_ would be appropriate, if attempting to restore a file-backed buffer which has gone missing (and also not creating the associated window).

**Comment by alphapapa** [comment]
I don't understand what's going on here.  A window configuration's restoration should not be affected by which window is selected.  As well, a warning is already implemented if a buffer cannot be restored; it looks like this:

![Screenshot_20240202_233735](https://github.com/alphapapa/activities.el/assets/601365/b456dbfb-73fd-4e63-9f37-28d48b7701ab)

The warning is shown in the correct buffer, and other windows and buffers are restored normally.  (It's always necessary to restore all windows, even if some buffers can't be restored, because windows can have child windows, so not restoring one could cause others to not be restored also.)

In order to solve this, I'll need an exact set of steps to reproduce the problem.

**Comment by jdtsmith** [comment]
1. Create three visible windows in a frame, with buffers visiting 3 files: `a.txt`, `b.txt`, `c.txt`.  
2. `M-x activities-new` (we'll call it `tmp`).   
3. Close the activity frame.  
4. Remove the file `c.txt` from disk.
5. `M-x activities-resume` `tmp`.

You should see an incorrect buffer in the place of `C` (even if the `c.txt` buffer is still alive!).  You can `activities-revert` from various windows in the `tmp` activity's frame, and different things will appear in `C`'s window, but not a warning, and not the `c.txt` buffer.  You can kill the (no file-less) `c.txt` buffer, and the behavior is the same.

**Comment by alphapapa** [comment]
Great, with that recipe I was able to reproduce and solve the problem (which is that the `bookmark` system obscures the error and works by side-effect, so we have to do some extra checking to be sure it worked).  Thanks for reporting this.  Please let me know if that fix works for you.
