### ISSUE TITLE
Don't hardcode activities-tabs-face foreground

### ISSUE THREAD

**Issue by karthink** [alphapapa/activities.el#24]
Enjoying this take on workspace management! Thank you for this package.

As a consequence of defining `activities-tabs-face` like this:
```elisp
(defface activities-tabs-face
  `((t :foreground ,(face-foreground 'font-lock-function-name-face nil 'default)))
  "Applied to tab-bar faces for tabs representing activities.")
```
the face does not change when the theme does, leading to mismatched/low-contrast tab bar name displays when I switch from a light to a dark theme.  Consider replacing this with some combination of `:inherit` and the tab-bar defaults?

**Comment by alphapapa** [comment]
Hi Karthik,

Thanks for the kind words.  I'm glad it's useful to you.

I understand the problem with theming, and I'd be glad to define the face in a better way, but since face inheritance is all-or-nothing, this was the best I could come up with to inherit just the foreground color.

But I do see that, e.g. with Prot's `ef-themes` and with the default Emacs theme, the `font-lock-function-name-face` only defines a foreground color, so I guess we can just inherit from it and hope that if other themes change it in other ways, it will turn out okay.  (And if not, the user can still customize it to fix it.)

I'll fix this in the next version.  Thanks for mentioning it.
