### ISSUE TITLE
seems to interfere with mu4e

### ISSUE THREAD

**Issue by danielgoldin** [alphapapa/activities.el#55]
I'm a non programmer who uses emacs on linux for academic papers. When I run mu4e under an activity, the index area gets periodically taken over by a pop-up message "*appease-gnus*. I'm really loving activities, but I also love using emacs for email. Thanks for any help.

**Comment by alphapapa** [comment]
Hi Daniel,

Thanks for the report.  Please provide a screenshot so I can understand what you mean.

**Comment by alphapapa** [comment]
I was linked by another user to:

* https://www.reddit.com/r/emacs/comments/q1podp/mu4e_new_message_view_popping_window_appeasegnus/
* https://groups.google.com/g/mu-discuss/c/JFXkBq7e-LY/m/kraUi1U1AAAJ?pli=1

After some digging, I see the problem now:

* https://github.com/djcb/mu/blob/3caa04fc2b5547611bb88022cb2aba0cc29bb894/mu4e/mu4e-view.el#L711 makes a fake summary buffer to appease Gnus's expectation that the summary buffer exists when https://github.com/djcb/mu/blob/3caa04fc2b5547611bb88022cb2aba0cc29bb894/mu4e/mu4e-view.el#L731 calls `gnus-article-prepare-display`.  It sets `gnus-summary-buffer` to that buffer.
* `gnus-article-prepare-display` puts the message rendering buffer into `gnus-article-mode`, which sets the buffer's `bookmark-make-record-function` to `gnus-summary-bookmark-make-record`.
* When `gnus-summary-bookmark-make-record` is called, it calls `gnus-article-show-summary`, which, as the comment says, "Go[es] back in summary buffer" (apparently then calling `(gnus-configure-windows 'article)`, which changes the window configuration accordingly).
* Dogears and Activities work by bookmarking the currently displayed buffers.  So whenever Dogears and Activities save bookmarks for a window configuration's buffers, and one of those buffers is one displaying a message rendered by `mu4e--view-render-buffer`, `gnus-summary-bookmark-make-record` makes the "appease" buffer visible.

It's hard to blame mu4e for doing this, as it was (and probably still is) necessary to appease Gnus's internal functions to reuse them this way.

AFAICT the simplest fix would be for `mu4e--view-render-buffer` to do something like `(kill-local-variable 'bookmark-make-record-function)` after rendering the message, which would prevent the `gnus-summary-bookmark-make-record` from being called.

This would generally be a correct thing to do, regardless of packages like Dogears and Activities triggering the problem, because the message buffer can't be bookmarked correctly, anyway (e.g. if the user did `C-x r m`, it would also trigger the problem, and the bookmark wouldn't work).

In the meantime, this workaround will probably do:
```el
(define-advice mu4e--view-render-buffer (:after (&rest _) unset-bookmark-make-record-function)
  (kill-local-variable 'bookmark-make-record-function))
```

**Comment by danielgoldin** [comment]
Works. Thanks!

--
Daniel Goldin
Editor, /Psychoanalytic Inquiry/
626-817-2462

**Comment by shrysr** [comment]
Thank you for the fix! fwiw - I wanted to add that this works for me as well.

**Comment by alphapapa** [comment]
Thanks.  Can anyone confirm whether the advice workaround is still needed for mu 1.12.3?  I ask because a different fix was applied to that branch of mu, and I don't know if it also fixes this problem.

**Comment by shrysr** [comment]
Adam Porter ***@***.***> writes:

> Thanks. Can anyone confirm whether the advice workaround is still needed for mu 1.12.3? I
> ask because a different fix was applied to that branch of mu, and I don't know if it also
> fixes this problem.

I upgraded to 1.12.4 (via homebrew) and without the advice workaround. The issue did not occur.

**Comment by alphapapa** [comment]
@shrysr 

> I upgraded to 1.12.4 (via homebrew) and without the advice workaround. The issue did not occur.

Great, thank you for reporting.
