### ISSUE TITLE
Other ways to handle unrestorable buffers

### ISSUE THREAD

**Issue by hab25** [alphapapa/activities.el#82]
My use-case: I use activities as a substitute for `desktop-mode` that improves the experience by  providing the added benefit of working for many non-file-backed buffers. 

I do this with code very similar to the following in at the top level of my `init.el`:

```emacs-lisp
(run-with-idle-timer
  5
  nil
  (lambda () 
	(let ((my/default-activity-name "my/default"))
        ;; side note: please make `#'activities-named` be autoloaded; as can be seen here, it is an appropriate entry point and would allow me to remove this `#'require`. 
	    (require 'activities)
	    (activities-resume
	      (or
	        (activities-named my/default-activity-name)
	        (activities-define my/default-activity-name))))))
```

However, in doing so, I often hit https://github.com/alphapapa/activities.el/blob/b63ccc58fc3b5b3e6ed5b74bf84bd4eff9bb1660/activities.el#L796 

Such a customization would allow me to avoid saving such buffers that cannot be restored.

**Comment by alphapapa** [comment]
Hello,

Adding such a predicate might be useful, but please help me understand your use case better.  What are you trying to do with that idle timer?

**Comment by alphapapa** [comment]
Thanks, but I'm still not sure I completely understand, because `activities` doesn't load an activity on Emacs startup.  Also, the function in the timer also calls `activities-define` sometimes.  Would you elaborate, please?

**Comment by alphapapa** [comment]
Forgive me, but you seem to have translated the Lisp into English, and I can already read code.  I'm asking about what you're trying to accomplish with that code.

**Comment by alphapapa** [comment]
Ok, thanks.  Generally it's best to lead with the root problem you're trying to solve rather than an incidental one several steps down the line--or, at least, to mention both.  (cf. "the XY problem)

Now, what kinds of buffers are you getting those errors for?  As I've mentioned elsewhere, the best solution is to make those buffers bookmarkable so they won't have such errors, and it usually doesn't take much code to do so.

**Comment by alphapapa** [comment]
Thanks for the examples.

Here are some thoughts:

1. A save-buffers predicate seems like an obvious thing to have, but it would also introduce another question: if a window's buffer does not pass the predicate, what should be done instead?  Should a previously displayed buffer in that window that does pass the predicate be saved instead?  That might not be useful.  Or, what if no such previously displayed buffer passes the predicate?  Should an error buffer be shown, as is currently the case, or should the window be deleted?  Deleting the window would likely be a bad idea, as it would corrupt the window configuration from what was set by the user.
2. Instead, what if the behavior of what to do in the case of an unrestoreable buffer were configurable?  e.g. rather than a buffer showing the error message as currently happens, what if the user could specify to show the scratch buffer, or something else?  This might be especially useful for your specific case, i.e. to only override the default behavior when restoring your last-used activity at startup.
3.  Another possibly useful option would be to save previous window configurations in the activity, ala `winner-mode` and `tab-bar-history-mode`, so that if some buffers weren't restorable, you could go back in the frame's/tab's window configuration history.

Well, those are the best ideas I have.  There is no perfect solution, other than having every major mode support bookmarks.  Certain ones, like profiler reports, are probably impractical and not very useful (although I could imagine a bookmark for the profiler report buffer saving and restoring the contents--that wouldn't seem too difficult, and it could be useful if a debugging session were interrupted).

Also, regarding terminal buffers: Having worked with this functionality for a while in `burly` and `bufler` before `activities`, having terminal buffers support bookmarks is an oft-requested feature.  There's probably no perfect solution, but it probably wouldn't be too hard to save the current working directory and open a new terminal to it when the bookmark is restored.  Of all the terminal emulator libraries, I'm guessing `eat` might be the one most suited to having such functionality (although Eshell is another obvious candidate), so I'd encourage you to discuss the idea with its maintainer.
