### ISSUE TITLE
`persist/activities-activities` can disappear during development

### ISSUE THREAD

**Issue by jdtsmith** [alphapapa/activities.el#87]
I have noticed that (rarely) the persist file `persist/activities-activities` has gone missing a couple of times during development (of #83).  It's possible this variable was somehow set to `nil`, and auto-save with persist deletes the file if this occurs, but I don't have a reasonable explanation for that.  I wanted to open this in case others have experienced this. 

One remedy might be to make the default value for that variable `'unspecified` or similar, that way it's unlikely for the variable's value to match, and for persist to remove the file.

**Comment by alphapapa** [comment]
Sorry, I was unclear.  I think this issue should be discussed with the `persist` maintainer.  It doesn't seem to have a repo outside of ELPA.git itself, so I guess we should discuss it on emacs-devel and/or file an Emacs bug report.  I'd rather not deal with it on this repo, since it's not really about `activities`.

**Comment by jdtsmith** [comment]
Understood, will keep an eye open for further instances (and keep a backup of my persist file handy).
